version: "3.6"

services:
  api:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    ports:
      - target: ${API_PORT:-5050}
        published: ${API_PORT:-5050}
        protocol: tcp
    container_name: ml_api
    volumes:
      - ../data:/code/data
    tty: true
    environment:
      API_MODULE: ${API_MODULE}
      WORKER_CLASS: ${WORKER_CLASS}
      WORKER_COUNT: ${WORKER_COUNT:-4}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
    healthcheck:
      test: curl --fail http://0.0.0.0:${API_PORT:-5050}/ || exit 1
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 60s
